VEGA-328: Разобраться со шрифтом на канве
gpn-prototypes/vega-ui pull request #198
Opened 2020-08-20 15:23 UTC by maksim-kononov-csssr

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Сторибук: stories соответствует [правилам](https://github.com/gpn-prototypes/vega-ui/blob/master/docs/storybook.md)
- [ ] Верстка: используются [переменные](https://github.com/gpn-prototypes/ui-kit/tree/master/src/components/Theme) и [css-классы](https://github.com/gpn-prototypes/ui-kit/blob/master/src/utils/whitepaper/whitepaper.css) из [дизайн-системы ГПН](https://github.com/gpn-prototypes/ui-kit)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-08-20 15:29 UTC, hitmanet approved these changes

2020-08-20 15:34 UTC, c1n1k requested changes
на винде не должны грузиться шрифты, укажи локальные имена в src

2020-08-20 16:27 UTC, maksim-kononov-csssr commented
> на винде не должны грузиться шрифты, укажи локальные имена в src

Кажется что виноват сам link rel=“preload” - он загружает ресурс и не важно есть он локально или нет

2020-08-25 06:38 UTC, c1n1k commented
на ie забиваем

2020-08-25 06:39 UTC, c1n1k commented on .storybook/preview-head.html
> +/> -->
коменты

2020-08-25 06:39 UTC, c1n1k approved these changes

2020-08-27 09:10 UTC, hitmanet commented
Вливаю в VEGA-345 для показа

2020-08-27 09:10 UTC, merged