Origin/vega 147
gpn-prototypes/vega-ui pull request #225
Opened 2020-09-01 10:39 UTC by DmitriiBo

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Сторибук: stories соответствует [правилам](https://github.com/gpn-prototypes/vega-ui/blob/master/docs/storybook.md)
- [ ] Верстка: используются [переменные](https://github.com/gpn-prototypes/ui-kit/tree/master/src/components/Theme) и [css-классы](https://github.com/gpn-prototypes/ui-kit/blob/master/src/utils/whitepaper/whitepaper.css) из [дизайн-системы ГПН](https://github.com/gpn-prototypes/ui-kit)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-09-01 10:57 UTC, ilchukovaolga commented
Необходимо добавить документацию к компоненту. Пример https://github.com/gpn-prototypes/vega-ui/tree/master/packages/components/navigation-list

2020-09-01 10:58 UTC, ilchukovaolga requested changes
1. Необходимо добавить документацию к компоненту. Пример https://github.com/gpn-prototypes/vega-ui/tree/master/packages/components/navigation-list
2. Необходимо заполнить чеклист в PR

2020-09-01 11:30 UTC, hitmanet commented
@DmitriiBo можешь поправить конфликты, а то сторибук не зальется

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/RootTreeNode.tsx
> +    return t.reduce((acc: Array<React.ReactElement>, node: NodeTreeType | LeafType) => {
не очень понятно, что тут происходит, здесь вложенное дерево строится?

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/Tree.css
> +  padding-right: 12px;
в переменных можно взять

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/Tree.css
> +  margin-bottom: 15px;
Разве там есть такой размер?

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/Tree.css
> +}
В файле нужно заменить все, что можно, на переменные из ДС

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/Tree.stories.tsx
> +      handleRename={() => alert('Renamed')}
В сб есть addon-action. Лучше заменить алерт на него

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/Tree.test.tsx
> +describe('Tree', () => {
не хватает тестов

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/Tree.tsx
> +export const Tree: React.FC<NodeTreeType> = (props) => {
Не совсем понятно, зачем выносить это в отдельный компонент

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/TreeNode.tsx
> +export const TreeNode: React.FC<NodeTreeType> = (props) => {
не понимаю чем этот компонент сильно отличается от Leaf

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/TreeNode.tsx
> +import {NodeTreeType} from './types';
Мы не пишем Type на конце типов

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/TreeNode.tsx
> +};
Компонент вроде как делает то же самое, что уже существующий Leaf

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/hooks.tsx
> +export function useOnClickOutside(ref: React.RefObject<HTMLElement>, handler: Handler) {
у нас уже есть такой хук в @gpn-prototypes/vega-hooks

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/hooks.tsx
> +export function useMultiSelect(handler: KeyUpHandler) {
и такой хук есть

2020-09-01 12:36 UTC, hitmanet commented on packages/components/tree/src/hooks.tsx
> +export function usePortal() {
и такой тоже

2020-09-01 12:37 UTC, hitmanet requested changes
Нужно удалить package-lock.json, прогнать линтер и дописать тесты. Ну и поправить/ответить на комменты

2020-09-01 15:41 UTC, DmitriiBo commented on packages/components/tree/src/TreeNode.tsx
> +};
NodeTree рендерит список и является droppable элементом в отличие от Leaf
Но в остальном они похожи :)

2020-09-02 06:43 UTC, c1n1k commented on packages/components/tree/src/Tree.css
> +ul {
плохая практика использовать теги напрямую

2020-09-02 06:53 UTC, c1n1k commented on packages/components/tree/src/Tree.css
> +.VegaTree__TreeRootNode {
почему не использовал сложенность `&__`?

2020-09-02 07:00 UTC, c1n1k commented on packages/components/tree/src/Tree.css
> +  background-image: url("data:image/svg+xml,%3Csvg width='12' height='8' viewBox='0 0 12 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M6 0C3.27273 0 0.943636 1.65867 0 4C0.943636 6.
так точно не пойдёт :)

2020-09-02 07:24 UTC, c1n1k commented on packages/components/tree/src/TreeNavigationEye.tsx
> +      role="button"
зачем? если семантически это кнопка, то почему не применить соотвествующий элемент?

2020-09-02 07:24 UTC, c1n1k commented on packages/components/tree/src/TreeNode.tsx
> +        <div
снова кнопка

2020-09-02 07:28 UTC, c1n1k commented on packages/components/tree/src/components/TreeContextMenu.tsx
> +        />
раздели на 2 компонента: 
1. Блок для контекстного меню с логикой позиционирования, которое принимает что угодно. И его лучше его сразу отдельный компонент и рендерить его надо в портале, иначе какой-нибудь `overflow` его «срежет»
2. Само меню

2020-09-02 07:48 UTC, c1n1k commented on packages/components/tree/src/components/TreeContextMenu.tsx
> +        />
для контекстного меню хорошо бы сделать хук для логики его отображения, примеры есть в хуках

2020-09-02 07:53 UTC, c1n1k commented on packages/components/tree/src/Tree.stories.tsx
> +    <Tree
дереву не всегда нужны линии слева, есть возможность их скрывать? не увидел в типах соответсвующий пропс

2020-09-02 07:57 UTC, c1n1k requested changes
в задаче есть требование `Должна быть настройка ограничений по перетаскиванию/копированию.` оно реализовано?

2020-09-02 11:54 UTC, DmitriiBo commented on packages/components/tree/src/Tree.css
> +.VegaTree__TreeRootNode {
c webstorm была проблема (ругался на синтаксис), только сегодня пофиксил
в дальнейшем буду реформатить и писать с вложенностью

2020-09-02 13:50 UTC, hitmanet commented
@DmitriiBo, если правишь что-то по нашим комментам, то нажимай resolve conversation, чтобы мы понимали, что ты это поправил
![image](https://user-images.githubusercontent.com/33551076/91992081-636b0480-ed3c-11ea-9b29-ef3631256f82.png)

2020-09-02 13:53 UTC, hitmanet commented
@DmitriiBo 
По поводу коммитов. Мы именуем их на русском языке согласно conventionnal commits. 
![image](https://user-images.githubusercontent.com/33551076/91992166-7c73b580-ed3c-11ea-858e-b872a0f663d9.png)
Merge-коммиты не особо приветствуем, лучше отребейзиться от ветки, в которую хочешь заливаться. Если не знаешь как, то приходи, покажу.
![image](https://user-images.githubusercontent.com/33551076/91992260-990fed80-ed3c-11ea-94f5-3604719ef0ea.png)

Ну и пустые коммиты тоже не ок
![image](https://user-images.githubusercontent.com/33551076/91992405-c492d800-ed3c-11ea-95ba-9c7aae1b10f9.png)

2020-09-02 13:57 UTC, hitmanet commented on packages/components/tree/src/Tree.css
> +  background-image: url("data:image/svg+xml,%3Csvg width='12' height='12' viewBox='0 0 12 12' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M1 9.
Старайся пожалуйста верстать без important, ну и по поводу урла, да, так не оч

2020-09-02 13:57 UTC, hitmanet commented on packages/components/tree/src/Tree.css
> +  z-index: 1;
z-index лучше вынести в css переменную

2020-09-02 13:57 UTC, hitmanet commented on packages/components/tree/src/TreeNode.tsx
> +};
Тогда лучше вынести общую часть в отдельный компонент

2020-09-02 19:09 UTC, c1n1k commented on packages/components/tree/src/hooks.tsx
> +export function useMultiSelect(handler: KeyUpHandler) {
пока ещё нет, он появится в следующем релизе ДС, а потом и в vega-ui

2020-09-02 19:16 UTC, c1n1k commented on packages/components/tree/src/Tree.css
> +  background-image: url("data:image/svg+xml,%3Csvg width='12' height='8' viewBox='0 0 12 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M6 0C3.27273 0 0.943636 1.65867 0 4C0.943636 6.
вынеси иконку в блок NavigationEye, когда иконка будет в разметке её будет проще заменить в случае чего, и управлять стилями можно будет в случае чего как svg иконки, так и её обёрткой

2020-09-03 06:33 UTC, DmitriiBo commented on packages/components/tree/src/hooks.tsx
> +export function useMultiSelect(handler: KeyUpHandler) {
хук такой не нашел, подумал, что ты имел в виду про useKey и его заюзал

2020-09-03 06:48 UTC, DmitriiBo commented on packages/components/tree/src/Leaf.tsx
> +    if (typeof props.handleHideItem === 'function') {
@hitmanet а если туда придет не функция, а другой тип данных?

2020-09-03 06:49 UTC, DmitriiBo commented on packages/components/tree/src/Leaf.tsx
> +      draggable={props.isDraggable === false ? "false" : "true"}
По умолчанию компонент с функциональностью ДНД, но ее можно выключить

2020-09-03 06:56 UTC, DmitriiBo commented on packages/components/tree/src/RootTreeNode.tsx
> +            isDraggable={props.isDraggable === false ? props.isDraggable : node.isDraggable}
Тут идет приоритет для значения, которое передали в компонент Tree , то есть если его хотят намеренно отключить, то значения из объекта node игнорируются

2020-09-03 07:18 UTC, hitmanet commented on packages/components/tree/src/Leaf.tsx
> +    if (typeof props.handleHideItem === 'function') {
вряд ли в проп-обработчик придет не функция
Ну максимум undefined

2020-09-03 07:20 UTC, hitmanet commented on packages/components/tree/src/Leaf.tsx
> +      draggable={props.isDraggable === false ? "false" : "true"}
ну сделай в пропсах по умолчанию isDraggable true

2020-09-03 07:28 UTC, DmitriiBo commented on packages/components/tree/src/Leaf.tsx
> +    if (typeof props.handleHideItem === 'function') {
Окей

2020-09-09 07:07 UTC, c1n1k commented on packages/components/tree/src/Tree.css
> +  background-color: var(--color-control-bg-active) !important;
`!important` надо убрать

2020-09-10 07:19 UTC, c1n1k commented
![](http://s.csssr.ru/UC5KAQ32R/2020-09-10-10-18-20-tfly0.png)

2020-09-10 07:21 UTC, c1n1k commented
я не могу переместить обратно элементы, которые вложил в другой ![](http://s.csssr.ru/UC5KAQ32R/2020-09-10-10-20-21-5bfsa.png) 
почему так? это требование такое?

2020-09-10 07:23 UTC, c1n1k commented on packages/components/tree/src/TreeItemContainer.tsx
> +      draggable={draggable && 'true'}
?

2020-09-10 07:26 UTC, hitmanet commented on packages/components/tree/src/TreeItemContainer.tsx
> +      draggable={draggable && 'true'}
можно просто `draggable={draggable}`

2020-09-10 08:15 UTC, c1n1k commented
Когда просил вынести контекстное меню, имел ввиду в отдельный пакет.
Дерево сейчас  как-то привязан больше к контексту конкретной задачи, лучше сделать его более абстрактным: иконки вообще отделить, они должны приниматься на вход, изначально все должно перемещаться куда угодно, а логику запретов передавать извне

2020-09-10 09:10 UTC, hitmanet commented on packages/components/tree/src/components/TreeContextMenu/TreeContextMenu.tsx
> +        left: contextMenuData?.style?.left,
а почему пропс необязательный? И лучше его тогда просто data назвать. И без поля style его сделать

2020-09-10 09:10 UTC, hitmanet commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +export const useContextMenu = ({ isContextMenuEnable }: useContextMenuProps): contextMenuApi => {
все-таки стоит вынести хук и компонент в отедльный пакет

2020-09-10 09:10 UTC, hitmanet commented on packages/components/tree/src/use-on-change-width.tsx
> +type WidthContainer = string | number | undefined;
а почему тут три типа? Нельзя как-то к одному привестм

2020-09-10 09:10 UTC, hitmanet commented on packages/components/tree/src/use-visability-identifier.tsx
> +export const useVisibilityIdentifier = ({
линтер ругается

2020-09-11 10:33 UTC, DmitriiBo commented on packages/components/tree/src/components/TreeContextMenu/TreeContextMenu.tsx
> +        left: contextMenuData?.style?.left,
тут не выйдет, мне в contextMenuData есть еще callerRef (реф элемента на котором было вызвано меню)

2020-09-11 10:53 UTC, DmitriiBo commented on packages/components/tree/src/TreeLeaf.tsx
> +      id={id?.toString()}
Исходил из того, что могут быть кейсы когда id не нужен совсем. (сделать простое дерево без интерактива)

2020-09-11 11:04 UTC, DmitriiBo commented on packages/components/tree/src/TreeLeaf.tsx
> +      id={id?.toString()}
Заменил тип на стринг, без приведения теперь передаю

2020-09-11 11:07 UTC, DmitriiBo commented on packages/components/tree/src/TreeItemContent.tsx
> +      {functionIcons && functionIcons}
Это массив реакт компонентов, кастомные навигационные иконки

2020-09-11 11:12 UTC, DmitriiBo commented on packages/components/tree/src/TreeItemContent.tsx
> +      {withVisibilitySwitcher && renderNavigationIcon && renderNavigationIcon()}
в данном случае тут рендерится VisibilitySwitcher, согласен, не совсем понятно, поменяю на renderVisibilitySwitcher

2020-09-11 11:13 UTC, ilchukovaolga requested changes

2020-09-11 11:13 UTC, ilchukovaolga commented on packages/components/tree/README.md
> +                    name: 'Еще что нибудь',
```suggestion
                    name: 'Еще что-нибудь',
```

2020-09-11 11:13 UTC, ilchukovaolga commented on packages/components/tree/README.md
> +    onPasteItem?: (transferringId, receivingId) => void; // Сработает при вставке и перенесении через DND узла в другой узел. Прокинет id переносимого элемента и принимающего.
```suggestion
    onPasteItem?: (transferringId, receivingId) => void; // Прокинет id переносимого элемента и принимающего. Сработает при вставке и перенесении через DND узла в другой узел.
```
Сначала что делает, потом когда.

2020-09-11 11:13 UTC, ilchukovaolga commented on packages/components/tree/README.md
> +    onRenameItem?: (id) => void; // Вызовет функцию, передав туда ID, при запросе переименовать узел дерева
```suggestion
    onRenameItem?: (id) => void; // Вызовет функцию, передав туда ID. При запросе необходимо переименовать узел дерева
```

2020-09-11 11:29 UTC, DmitriiBo commented on packages/components/tree/src/TreeItemContent.tsx
> +      {iconId && icons && <div className={cnTree('Icon')}>{icons[iconId]}</div>}
icons - иконки слева от названия, functionIcons - кастомные навигационные иконки, наподобие visibilitySwitcher

2020-09-11 11:46 UTC, DmitriiBo commented on packages/components/tree/src/Tree.css
> +  box-shadow: 0 2px 2px rgba(0, 0, 0, 0.04), 0 4px 16px rgba(0, 32, 51, 0.18);
нет такой

2020-09-11 11:49 UTC, DmitriiBo commented on packages/components/tree/README.md
> +    iconId?: string | number; // ID иконки, которая мэтчится с названием из коллекции ICONS
поправил на соответствует :)

2020-09-11 11:50 UTC, DmitriiBo commented on packages/components/tree/README.md
> +    isDraggable?: boolean; // Возможность ограничить функциональность DragAndDrop для некоторых элементов
Получается, что выключить, поправил

2020-09-11 11:52 UTC, DmitriiBo commented on packages/components/tree/README.md
> +    isContextMenuEnable?: boolean; // Возможность добавить контекстное меню. По умолчанию выключено.
Решил сделать в терминологии включено/выключено

2020-09-11 11:54 UTC, DmitriiBo commented on packages/components/tree/README.md
> +    onRenameItem?: (id) => void; // Вызовет функцию, передав туда ID, при запросе переименовать узел дерева
Решил сделать так:
Функция-обработчик, которая вызывается при попытке переименовать аргумент

2020-09-11 12:39 UTC, hitmanet commented on packages/components/tree/src/TreeItemContent.tsx
> +      {iconId && icons && <div className={cnTree('Icon')}>{icons[iconId]}</div>}
а нельзя это как-то универсализировать? или изменить название у functionIcons?

2020-09-11 12:40 UTC, hitmanet commented on packages/components/tree/src/TreeLeaf.tsx
> +      id={id?.toString()}
мне кажется, у элементов дерева всегда должен быть id. Вряд ли будет кейс, где так будет

2020-09-11 12:40 UTC, hitmanet commented on packages/components/tree/src/TreeLeaf.tsx
> +      id={id?.toString()}
id нужен хотя бы для того, чтобы key в реакте проставить

2020-09-11 12:41 UTC, hitmanet commented on packages/components/tree/src/components/TreeContextMenu/TreeContextMenu.tsx
> +        left: contextMenuData?.style?.left,
может тогда сделать его обязательным и переименовать? Или просто уйти от дополнительного объекта, а передавать callerRef и style отдельно, чтобы разделить пропсы

2020-09-11 13:56 UTC, DmitriiBo commented on packages/components/tree/src/TreeItemContent.tsx
> +      {iconId && icons && <div className={cnTree('Icon')}>{icons[iconId]}</div>}
да, лучше поменяю название

2020-09-11 14:04 UTC, DmitriiBo commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +export const useContextMenu = ({ isContextMenuEnable }: useContextMenuProps): contextMenuApi => {
да, буду оформлять еще один ПР

2020-09-11 15:12 UTC, DmitriiBo commented on packages/components/tree/src/components/TreeContextMenu/TreeContextMenu.tsx
> +        left: contextMenuData?.style?.left,
ага, разнес на разные сущности))

2020-09-14 09:28 UTC, ababakov commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +export const useContextMenu = ({ isContextMenuEnable }: useContextMenuProps): contextMenuApi => {
@hitmanet Вопрос организационный - вынесли в отдельную таску https://jira.csssr.io/browse/VEGA-324 <- https://jira.konakov.tv/browse/INTERFACE-41

2020-09-14 09:28 UTC, hitmanet commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +export const useContextMenu = ({ isContextMenuEnable }: useContextMenuProps): contextMenuApi => {
хорошо

2020-09-14 14:12 UTC, DmitriiBo commented on packages/components/tree/src/TreeLeaf.tsx
> +      id={id?.toString()}
ну в целом да) сделал обязательным)

2020-09-14 16:58 UTC, DmitriiBo commented
> я не могу переместить обратно элементы, которые вложил в другой ![](https://camo.githubusercontent.com/1e74cccaf28643dd0cb43d2170db58a9895cccbb/687474703a2f2f732e63737373722e72752f5543354b41513332522f323032302d30392d31302d31302d32302d32312d35626673612e706e67)
> почему так? это требование такое?

Поменял логику, сейчас можно, ранее я ограничивал возможность дропать элемент в зону, которая уже содержит его

2020-09-15 09:00 UTC, hitmanet commented
@DmitriiBo удалить package-lock пожалуйста

2020-09-15 09:06 UTC, hitmanet commented on packages/components/layout/docs/grid.md
> +interface TreeLeaf<T> {
а почему здесь Layout затронули и NavigationList?

2020-09-15 09:06 UTC, hitmanet commented on packages/components/tree/src/Tree.tsx
> +      selectedItems?.some((item) => {
вынеси это из ифа пожалуйста

2020-09-15 09:06 UTC, hitmanet commented on packages/components/tree/src/Tree.tsx
> +      // eslint-disable-next-line no-unused-expressions
почему тут заглушен?

2020-09-15 09:33 UTC, DmitriiBo commented on packages/components/layout/docs/grid.md
> +interface TreeLeaf<T> {
оу, видимо случайно... поправил

2020-09-15 09:37 UTC, DmitriiBo commented on packages/components/tree/src/Tree.tsx
> +      // eslint-disable-next-line no-unused-expressions
поправил

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/TreeNode.tsx
> +  const visibilityIdentifier = useVisibilityIdentifier({ ref: targetRef, handleHide, hiddenItems });
не совсем понимаю, что возвращает этот хук

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/TreeNode.tsx
> +  const handleExpand = (event: React.MouseEvent | React.KeyboardEvent): void => {
тут скорее handleToggleExpand

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/TreeNode.tsx
> +  const handleDragEnter = (event: React.DragEvent): void => {
можно ж в компоненте в который передаешь сделать эти пропсы опкциональными и тогда избавиться от кучи обработчиков

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/TreeNode.tsx
> +        data-container-id={id?.toString()}
все еще id почему-то необязательный

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +  closeContextMenu: () => void;
просто close

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +  handleContextMenu: (event: React.MouseEvent, ref: React.RefObject<HTMLElement>) => void;
просто open

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +  const [menuCoordinates, setCoordinates] = useState<{
Я бы по дефолту задал что-нибудь, чтобы риск падения с ошибкой снизить

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/context.ts
> +const TreeContext = React.createContext<TreeApi>({});
может лучше сделать все поля обязательными, но задать им дефолтные значения?

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/types.ts
> +export type RootProps = NodeItem[];
кажется, что тип для пропсов лучше держать рядом с компонентом

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/use-on-change-width.tsx
> +export function useOnChangeTreeWidth(
как я и писал выше, лучше вынести это в отдельный хук

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/use-on-change-width.tsx
> +export function useOnChangeTreeWidth(
в общие хуки, изолировать и покрыть тестами

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/use-on-change-width.tsx
> +export function useOnChangeTreeWidth(
и добавить функциональности

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/use-visability-identifier.tsx
> +const NavigationDot: React.FC = () => (
мне кажется, не оч иконку держать рядом с хуком, лучше вынести отдельно, а еще тип тут лучше использовать ReactElement

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/use-visability-identifier.tsx
> +type VisibilityIdentifierData = 'children' | 'parent' | null;
тогда уж `typeof children | typeof parent | null`

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/use-visability-identifier.tsx
> +type VisibilityIdentifierData = 'children' | 'parent' | null;
а лучше `children | parent | null`

2020-09-16 11:34 UTC, hitmanet commented on packages/components/tree/src/use-visability-identifier.tsx
> +      hiddenItems?.some((_ref: React.RefObject<HTMLElement>) => {
лучше вынести это из ифа

2020-09-16 12:09 UTC, DmitriiBo commented on packages/components/tree/src/Tree.tsx
> +    setHiddenItems([ref]);
тут лишняя, убрал

2020-09-16 13:02 UTC, DmitriiBo commented on packages/components/tree/src/TreeNode.tsx
> +        data-container-id={id?.toString()}
уже обязательный, забыл тут поменять

2020-09-16 13:07 UTC, DmitriiBo commented on packages/components/tree/src/context.ts
> +const TreeContext = React.createContext<TreeApi>({});
где мог задал и сделал обязательными

2020-09-16 13:09 UTC, hitmanet approved these changes

2020-09-16 13:19 UTC, Inzephirum commented on packages/components/tree/src/use-on-change-width.tsx
> +  useEffect(() => {
тут лучше использовать `useLayoutEffect`, потому что далее идет вызов `updateWidth()`. Из-за этого может быть дергание размеров.

2020-09-16 13:19 UTC, Inzephirum commented on packages/components/tree/src/use-on-change-width.tsx
> +type WidthContainer = number;
читается как будто тут должен быть элемент, а не его ширина, лучше наоборот сделать `ContainerWidth`

2020-09-16 13:19 UTC, Inzephirum commented on packages/components/tree/src/types.ts
> +export type ContextMenuListProps = Omit<ContextMenuProps, 'menuCoordinates' | 'closeContextMenu'>;
думаю будет удобней хранить типы компонентов рядом с самими компонентами

2020-09-16 13:19 UTC, Inzephirum commented on packages/components/tree/src/use-visability-identifier.tsx
> +    visibilityIdentifierData: !!visibilityIdentifierData,
для чего тут приведение к `boolean` ?

2020-09-16 13:19 UTC, Inzephirum commented on packages/components/tree/src/use-visability-identifier.tsx
> +        return _ref.current?.contains(ref.current as Node);
Лучше стараться избегать использование приведения типов вроде `ref.current as Node`. Если тут может быть другой тип, то лучше его обработать.

2020-09-16 13:19 UTC, Inzephirum commented on packages/components/tree/src/components/TreeContextMenu/TreeContextMenuList.tsx
> +  // };
это случайно закомментировано?

2020-09-16 13:19 UTC, Inzephirum commented on packages/components/tree/src/Tree.tsx
> +        );
`TreeNode` и  `TreeLeaf` очень похожи. Кажется это можно сделать одним компонентом, который будет рекурсивно сам себя рендерить.

2020-09-16 13:22 UTC, Inzephirum commented
Нашел две баги:
1. Если развернуть какой-нибудь элемент, то сворачивается он только по второму клику.
2. Контекстное меню не закрывается по клику на пункт меню (возможно не баг)

Еще думаю стоит сделать обработку состояния (копирование, удаление и прочее) в сторисе.

2020-09-16 13:23 UTC, DmitriiBo commented on packages/components/tree/src/Tree.tsx
> +        );
уже обсуждали этот момент с Димой Клименко, вынести полностью не получилось, но выделил общие части

2020-09-16 13:43 UTC, Inzephirum commented on packages/components/tree/src/Tree.tsx
> +        );
можешь, пожалуйста, скинуть ссылку на диалог?

2020-09-16 13:48 UTC, hitmanet commented on packages/components/tree/src/Tree.tsx
> +        );
это в хенгаутсе было и я немного про другое говорил. В целом сейчас я согласен с Сергеем

2020-09-16 15:28 UTC, DmitriiBo commented on packages/components/tree/src/use-visability-identifier.tsx
> +    visibilityIdentifierData: !!visibilityIdentifierData,
Для рендера visibilitySwitcher (который глазик)
{ Hidden: visibilityIdentifier.visibilityIdentifierData }
Сделал приведение к boolean, чтобы не избавиться от дополнительного свойства isHidden

2020-09-16 15:29 UTC, DmitriiBo commented on packages/components/tree/src/components/TreeContextMenu/TreeContextMenuList.tsx
> +  // };
по меню решили, что будем выносить в отдельный ПР, это просто уберу

2020-09-16 15:38 UTC, DmitriiBo commented
> Нашел две баги:
> 
> 1. Если развернуть какой-нибудь элемент, то сворачивается он только по второму клику.
> 2. Контекстное меню не закрывается по клику на пункт меню (возможно не баг)
> 
> Еще думаю стоит сделать обработку состояния (копирование, удаление и прочее) в сторисе.

1. Заметил баг, но только при спаме кликами. В штатном режиме все ок) попробую подебажить конечно
2.Не баг, но как возьмусь за меню в отдельном ПР еще уточню этот момент

2020-09-16 15:50 UTC, DmitriiBo commented on packages/components/tree/src/Tree.tsx
> +    e.stopPropagation();
лишнее, убрал))

2020-09-16 15:53 UTC, DmitriiBo commented on packages/components/tree/src/Tree.tsx
> +        item.ref?.current?.draggable === false
ты имеешь в виду про поле draggable?

2020-09-16 15:54 UTC, DmitriiBo commented on packages/components/tree/src/Tree.css
> +    & > * {
не получится, мне нужно применить стили к дочерним элементам, которые компонент Дерево принимает из вне

2020-09-16 15:56 UTC, DmitriiBo commented on packages/components/tree/README.md
> +    isShownLeftLines?: boolean; // Отвечает за показ линий слева от узлов дерева. По умолчанию включены.
долго думал как же их обозвать :)

2020-09-16 16:08 UTC, DmitriiBo commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +    }
пока сделал что, если у нас запрещено контекстное меню, то открытие не произойдет

2020-09-16 16:10 UTC, DmitriiBo commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +    }
во второй итерации буду это развязывать

2020-09-16 16:12 UTC, DmitriiBo commented on packages/components/tree/src/components/TreeContextMenu/use-context-menu.tsx
> +  };
да, с меню пока уже все на стоп. это будет отдельный ПР

2020-09-16 16:14 UTC, DmitriiBo commented on packages/components/tree/src/use-on-change-width.tsx
> +  useEffect(() => {
точно :)

2020-09-16 16:51 UTC, Inzephirum commented on packages/components/tree/src/Tree.tsx
> +        item.ref?.current?.draggable === false
Да, в том числе. Еще где `item.ref?.current?.contains()`. Вроде это все можно вычислить из состояния

2020-09-16 19:26 UTC, DmitriiBo commented on packages/components/tree/src/Tree.tsx
> +        item.ref?.current?.draggable === false
item.ref?.current?.contains() - это не получится из состояния вычислить, у меня там нет инфы какого нибудь groupId

2020-09-16 19:30 UTC, DmitriiBo commented on packages/components/tree/README.md
> +type NodeItem = {
TreeItem думаю самое то!))

2020-09-17 06:56 UTC, c1n1k commented on packages/components/tree/src/Tree.css
> +    & > * {
что-то напрягает меня такое, будет лишний код если понадобится переопределить, ещё и вес селектора повышать

2020-09-17 11:36 UTC, DmitriiBo commented on packages/components/tree/src/Tree.test.tsx
> +      expect(item.className.includes('VegaTree__NavigationItem_Selected')).toBe(true);
делал по примеру уже готовых компонентов

2020-09-21 06:52 UTC, c1n1k approved these changes

2020-09-21 08:21 UTC, ilchukovaolga requested changes

2020-09-21 08:21 UTC, ilchukovaolga commented on packages/components/tree/README.md
> +    withVisibilitySwitcher?: boolean; // Позволяет отключить иконку скрывающую элемент Дерева. При нажатии меняет стилизацию своего родителя. По умолчанию включено.
```suggestion
    withVisibilitySwitcher?: boolean; // Позволяет отключить иконку, скрывающую элемент Дерева. При нажатии меняет стилизацию своего родителя. По умолчанию включено.
```

2020-09-21 08:21 UTC, ilchukovaolga commented on packages/components/tree/README.md
> +            isDndEnable={false} // Отключит Drag and Drop для всего дерева
```suggestion
            isDndEnable={false} // Отключит Drag and Drop для всего Дерева
```
Ниже написание компонента встречается с заглавной буквы. Нужно единообразие

2020-09-21 08:21 UTC, ilchukovaolga commented on packages/components/tree/README.md
> +    showIndentGuides?: boolean; // Отвечает за показ линий слева от узлов дерева. По умолчанию включены.
```suggestion
    showIndentGuides?: boolean; // Отвечает за показ линий слева от узлов Дерева. По умолчанию включены.
```

2020-09-21 08:28 UTC, ilchukovaolga approved these changes

2020-09-23 13:55 UTC, Inzephirum approved these changes

2020-09-23 13:56 UTC, merged