feat(components): добавление тултипа для иконки глаза
gpn-prototypes/vega-ui pull request #288
Opened 2020-10-06 06:56 UTC by DmitriiBo

Тултип при наведении на иконку глаза "Показать"/"Скрыть". Дополнительно заменил className -> ref в
хуке useOnChangeWidth, и добавил возможность отдавать наружу переносимые элементы на событии
onDragStart

Jira issue: VEGA-1599

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Сторибук: stories соответствует [правилам](https://github.com/gpn-prototypes/vega-ui/blob/master/docs/storybook.md)
- [ ] Верстка: используются [переменные](https://github.com/gpn-prototypes/ui-kit/tree/master/src/components/Theme) и [css-классы](https://github.com/gpn-prototypes/ui-kit/blob/master/src/utils/whitepaper/whitepaper.css) из [дизайн-системы ГПН](https://github.com/gpn-prototypes/ui-kit)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-10-06 07:21 UTC, c1n1k commented on packages/components/tree/src/TreeNavigationEye.tsx
> +        <Tooltip isInteractive={false} position={position} size="s" direction="upCenter">
позиционирование надо чуть доработать
![](http://s.csssr.ru/UC5KAQ32R/2020-10-06-10-18-59-iv3dh.png)

2020-10-06 15:45 UTC, c1n1k commented on packages/components/tree/src/TreeNavigationEye.tsx
> +          possibleDirections={['upCenter']}
не надо настраивать позиционирование, эта логика есть уже в тултипе есть, добавь [возможные направления появления](https://consta-uikit.vercel.app/?path=/docs/components-popover--popover-positioned-by-coords-story#%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D0%B7%D0%B2%D0%BE%D1%80%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F).

![](http://s.csssr.ru/UC5KAQ32R/2020-10-06-18-38-41-xw81c.png)

баг с контекстным меню, его так же можно в поповере можно попробовать выводить, чтобы позиционирование не настраивать
![](http://s.csssr.ru/UC5KAQ32R/2020-10-06-18-40-05-7nwtc.png)

2020-10-06 15:45 UTC, c1n1k requested changes
ошибки с позиционированием

2020-10-06 15:47 UTC, DmitriiBo commented on packages/components/tree/src/TreeNavigationEye.tsx
> +          possibleDirections={['upCenter']}
с контекстным меню в отдельной задаче буду делать
а с вшитым позиционированием проблема, он смещается влево и слишком высоко от иконки

2020-10-06 16:12 UTC, DmitriiBo commented on packages/components/tree/src/TreeNavigationEye.tsx
> +          possibleDirections={['upCenter']}
!(https://user-images.githubusercontent.com/43147386/95228344-e124a300-0807-11eb-8982-02a1bbdf8b63.png)

2020-10-06 16:13 UTC, DmitriiBo commented on packages/components/tree/src/TreeNavigationEye.tsx
> +          possibleDirections={['upCenter']}
![Снимок экрана от 2020-10-06 19-02-08](https://user-images.githubusercontent.com/43147386/95228470-0ca78d80-0808-11eb-8d65-4bd2ae6365b4.png)

2020-10-06 16:43 UTC, DmitriiBo commented
Создал issue по некорректному позиционированию тултипа https://github.com/gazprom-neft/consta-uikit/issues/490

2020-10-07 06:25 UTC, c1n1k approved these changes

2020-10-07 06:58 UTC, hitmanet approved these changes

2020-10-07 15:39 UTC, DmitriiBo commented
по невозможности кастомизации тултипа создал ишью: https://github.com/gazprom-neft/consta-uikit/issues/495

2020-10-07 16:50 UTC, dmitriy-0297 commented
Исправлена и проверена задача с иконками - https://jira.konakov.tv/browse/VEGA-1712

2020-10-08 06:42 UTC, merged