VEGA-876: Покрыть тестами layout
gpn-prototypes/vega-ui pull request #497
Opened 2021-02-03 19:39 UTC by c1n1k

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [x] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Сторибук: stories соответствует [правилам](https://github.com/gpn-prototypes/vega-ui/blob/master/docs/storybook.md)
- [ ] Верстка: используются [переменные](https://github.com/gpn-prototypes/ui-kit/tree/master/src/components/Theme) и [css-классы](https://github.com/gpn-prototypes/ui-kit/blob/master/src/utils/whitepaper/whitepaper.css) из [дизайн-системы ГПН](https://github.com/gpn-prototypes/ui-kit)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [x] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2021-02-08 06:55 UTC, fixmylie commented on src/components/layout/Layout.test.tsx
> +      act(() => {
А без актов будет варнинги кидать? Просто в доке написано, что все события уже обернуты в акты.
`Passes it to the @testing-library/dom fireEvent. It's also wrapped in act so you don't need to worry about doing it.`.

2021-02-08 07:16 UTC, maksim-kononov-csssr commented on src/components/layout/Layout.test.tsx
> +      act(() => {
Вот тут: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library/#wrapping-things-in-act-unnecessarily

2021-02-08 07:22 UTC, maksim-kononov-csssr approved these changes

2021-02-09 06:20 UTC, Inzephirum requested changes

2021-02-09 06:20 UTC, Inzephirum commented on src/components/layout/grid/Tree.test.ts
> +    expect(tree.extract()[max].type).toBe('leaf');
Тут лучше иначе проверить

```ts
let [max, node] = tree.max();

expect(max).toBe(0);
expect(tree.indexOf(node)).toBe(max);
```
тип элемента тут можно не проверять

2021-02-09 06:20 UTC, Inzephirum commented on src/components/layout/grid/Tree.test.ts
> +    expect(max).toBe(2);
```suggestion
    [max] = tree.max();
    expect(max).toBe(2);
```

2021-02-09 06:20 UTC, Inzephirum commented on src/components/layout/grid/Tree.test.ts
> +      // правый узел
левый же

2021-02-09 06:20 UTC, Inzephirum commented on src/components/layout/grid/Tree.test.ts
> +        1: Node.createLeaf(),
состояние невалидное, у branch должно быть два leaf

2021-02-09 06:20 UTC, Inzephirum commented on src/components/layout/grid/Tree.test.ts
> +      expect(tree.extract()[0].type).toBe('branch');
Не должно так быть. Если у branch нет leaf, то это должен быть leaf

2021-02-09 06:20 UTC, Inzephirum commented on src/components/layout/grid/Tree.test.ts
> +      expect(tree.extract()[0].type).toBe('branch');
а где здесь проверяется замена (исходя из описания теста) ?

2021-02-09 06:20 UTC, Inzephirum commented on src/components/layout/grid/Tree.ts
> +  public max(): TreeEntry {
:+1:

2021-02-09 06:20 UTC, Inzephirum commented on src/hooks/use-window-size/use-window-size.test.tsx
> +  test('размер окна отображается в компоненте', () => {
:+1:

2021-02-09 06:20 UTC, Inzephirum commented on src/hooks/use-window-size/use-window-size.test.tsx
> +  test('размер окна отображается в компоненте', () => {
но лучше бы не в этой задаче)

2021-02-09 06:55 UTC, c1n1k commented on src/components/layout/LayoutMenu/LayoutMenuList.test.tsx
> +// }
удалил

2021-02-09 06:56 UTC, c1n1k commented on src/components/layout/grid/Cursor.test.ts
> +  });
исправил

2021-02-09 06:57 UTC, c1n1k commented on src/components/layout/Layout.test.tsx
> +      });
удалил

2021-02-09 06:58 UTC, c1n1k commented on src/components/layout/grid/DataView.test.ts
> +describe('SplitView', () => {
исправил

2021-02-09 06:58 UTC, c1n1k commented on src/components/layout/grid/DataView.test.ts
> +  test('возвращает ошибку если невозможно создать SplitView', () => {
исправил

2021-02-09 12:19 UTC, hitmanet commented on src/components/layout/Layout.test.tsx
> +      expect(screen.getAllByRole('button')[0]).toHaveTextContent('Widget 1');
а ведь в какой-то момент она может стать не первой.

2021-02-09 12:19 UTC, hitmanet commented on src/components/layout/Layout.test.tsx
> +            return 100;
То есть тут в любом случае 100 вернется?

2021-02-09 15:51 UTC, c1n1k commented on src/components/layout/Layout.test.tsx
> +      expect(screen.getAllByRole('button')[0]).toHaveTextContent('Widget 2');
изменил

2021-02-09 15:58 UTC, c1n1k commented on src/components/layout/grid/Cursor.ts
> +    /* istanbul ignore else */
теперь не нужен

2021-02-09 16:12 UTC, c1n1k commented on src/components/layout/grid/DataView.test.ts
> +    }
исправил

2021-02-09 16:15 UTC, c1n1k commented on src/components/layout/grid/Grid.test.tsx
> +    }
заменил

2021-02-09 16:18 UTC, c1n1k commented on src/components/layout/grid/SplitView.test.ts
> +    try {
исправил

2021-02-09 16:19 UTC, c1n1k commented on src/components/layout/grid/SplitView.test.ts
> +      sv.getBreakpoint();
уже не актуально

2021-02-09 16:27 UTC, c1n1k commented on src/components/layout/grid/Tree.test.ts
> +    expect(tree.extract()[max].type).toBe('leaf');
исправил

2021-02-09 16:29 UTC, c1n1k commented on src/components/layout/grid/Tree.test.ts
> +    expect(max).toBe(2);
заменил

2021-02-09 16:30 UTC, c1n1k commented on src/components/layout/grid/Tree.test.ts
> +      // правый узел
исправил

2021-02-09 16:32 UTC, c1n1k commented on src/components/layout/grid/Tree.test.ts
> +      expect(tree.extract()[0].type).toBe('branch');
исправил

2021-02-09 16:32 UTC, c1n1k commented on src/components/layout/grid/Tree.test.ts
> +        1: Node.createLeaf(),
исправил

2021-02-09 16:39 UTC, c1n1k commented on src/components/layout/grid/Tree.test.ts
> +      expect(tree.extract()[0].type).toBe('branch');
добавил проверку на `branch`

2021-02-11 06:39 UTC, c1n1k commented on src/components/layout/Layout.test.tsx
> +      expect(screen.getAllByRole('button')[0]).toHaveTextContent('Widget 1');
изменил, теперь ищется по label

2021-02-11 11:20 UTC, Inzephirum commented on src/components/layout/grid/Tree.test.ts
> +    try {
остался try catch

2021-02-11 11:20 UTC, Inzephirum commented on src/components/layout/LayoutMenu/LayoutMenu.test.tsx
> +    expect(screen.queryByRole('aria-current')).not.toBeInTheDocument();
такой роли же быть не может

2021-02-11 17:17 UTC, c1n1k commented on src/components/layout/grid/Tree.test.ts
> +    try {
удалил

2021-02-11 17:18 UTC, c1n1k commented on src/components/layout/LayoutMenu/LayoutMenu.test.tsx
> +    expect(screen.queryByRole('aria-current')).not.toBeInTheDocument();
изменил тест

2021-02-11 17:18 UTC, c1n1k commented on src/components/layout/Layout.test.tsx
> +            return 100;
исправил, чтобы возвращалось 100

2021-02-12 07:49 UTC, Inzephirum approved these changes

2021-02-12 08:25 UTC, ilchukovaolga approved these changes

2021-02-12 08:51 UTC, merged