VEGA-879: Покрыть тестами scale-panel
gpn-prototypes/vega-ui pull request #504
Opened 2021-02-05 12:12 UTC by c1n1k

## Описание изменений

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [x] JS: нет варнингов и ошибок в консоли браузера
- [x] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Сторибук: stories соответствует [правилам](https://github.com/gpn-prototypes/vega-ui/blob/master/docs/storybook.md)
- [ ] Верстка: используются [переменные](https://github.com/gpn-prototypes/ui-kit/tree/master/src/components/Theme) и [css-классы](https://github.com/gpn-prototypes/ui-kit/blob/master/src/utils/whitepaper/whitepaper.css) из [дизайн-системы ГПН](https://github.com/gpn-prototypes/ui-kit)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [x] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2021-02-08 05:49 UTC, fixmylie requested changes

2021-02-08 05:49 UTC, fixmylie commented on src/components/scale-panel/ScalePanel.test.tsx
>      test('обработка некорректного значения #1', () => {
Очень неинформативное описание. 
`берется только цифровое значение при вводе` было бы лучше.
Ну и остальные кейсы тоже бы подумать над описание

2021-02-08 05:49 UTC, fixmylie commented on src/components/scale-panel/ScalePanel.test.tsx
> +    test('обработка некорректного значения #3', () => {
тоже поправить описание

2021-02-08 07:12 UTC, maksim-kononov-csssr commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
Я не понимаю тут логики
1) В каких случаях мы введем не строку "null", а именно значение null?
2) Почему onChange должен вызваться с максимальным значением?

2021-02-08 07:12 UTC, maksim-kononov-csssr commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
В обработчике handleChange даже тип описан как `value: string | null` в каких случаях там null ожидается получить?

2021-02-08 07:13 UTC, maksim-kononov-csssr commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
Например в handleSubmit есть обработка
`if (Number.isNaN(number)) {
      setValue(scale.toString());
      return;
}` - если на вход нам поступило что-то нехорошее, то откатимся к значению scale, а в handleChange значение по умолчанию для похожего случая пустая строка

2021-02-08 07:22 UTC, c1n1k commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
1. я проверил условие что null обрабатывется правильно, а как оно может «прилелеть» уже другое дело
2. потому что есть предельно допустимые значения и они должны обрабатываться передаваться если были введено значение не входящее в отрезок допустимых

2021-02-08 08:05 UTC, maksim-kononov-csssr commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
Я все еще не понимаю почему передается максимальное значение, а не минимальное например.
На мой взгляд естественно чтобы передавалось предварительно установленное значение - scale, в данном случае равное 100

2021-02-08 08:20 UTC, Inzephirum commented on src/components/scale-panel/ScalePanel.test.tsx
> +      fireEvent.click(findZoomOut());
давай тут тоже везде на userEvent поменяем?

2021-02-08 14:55 UTC, c1n1k commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
тут разницы нет, хоть что передавай, а в функцию должны прилететь пограничные значения, если пользователь ввёл не входящее в допустимый отрезок т.е. от 20 до 150, всё что больше 150 заменяется на 150, всё что меньше 20 заменяться на 20

2021-02-08 16:20 UTC, c1n1k commented on src/components/scale-panel/ScalePanel.test.tsx
> +    fireEvent.keyUp(input, { key: 'Enter' });
что-то безуспешно

2021-02-08 16:24 UTC, c1n1k commented on src/components/scale-panel/ScalePanel.test.tsx
> +      fireEvent.click(findZoomOut());
заменил

2021-02-09 02:53 UTC, fixmylie approved these changes

2021-02-09 05:05 UTC, Inzephirum commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
так а в инпут же нельзя ввести `null`, там в любом случае будет строка.

2021-02-09 06:52 UTC, c1n1k commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
мне нужно проверить как-то условие в обработчике, для этого и сделал такой тест, убрать эту проверку приведёт к пляскам с типами, потому что этот обработчик передается в textfield

2021-02-09 12:15 UTC, hitmanet approved these changes

2021-02-09 12:15 UTC, hitmanet commented on src/components/scale-panel/ScalePanel.test.tsx
> +      renderComponent({});
зачем передавать пустой объект, если это и так значение по дефолту?

2021-02-09 19:08 UTC, c1n1k commented on src/components/scale-panel/ScalePanel.test.tsx
> +      renderComponent({});
удалил

2021-02-10 09:11 UTC, Inzephirum commented on src/components/scale-panel/ScalePanel.test.tsx
> +    });
Просто очень странный тест, ведь пользователь не может ввести `null`. Тут нужно либо изменить условие, чтобы обрабатывались только строки, либо вообще заигнорить coverage.

2021-02-11 11:06 UTC, Inzephirum approved these changes

2021-02-12 09:12 UTC, merged