VEGA-3176: [CANVAS] Позиция экрана и скролла сохраняются отдельно для каждого project-id
gpn-prototypes/vega-ui pull request #513
Opened 2021-02-12 16:38 UTC by DmitriiBo

Jira issue: VEGA-3176

## Описание изменений

 - Добавление идентификатора проекта в ключ доступа к позиции скролла и фокуса из session storage

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Сторибук: stories соответствует [правилам](https://github.com/gpn-prototypes/vega-ui/blob/master/docs/storybook.md)
- [ ] Верстка: используются [переменные](https://github.com/gpn-prototypes/ui-kit/tree/master/src/components/Theme) и [css-классы](https://github.com/gpn-prototypes/ui-kit/blob/master/src/utils/whitepaper/whitepaper.css) из [дизайн-системы ГПН](https://github.com/gpn-prototypes/ui-kit)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2021-02-15 06:58 UTC, hitmanet commented on src/components/canvas/utils.ts
> +export const getProjectIdFromURI = (): string | undefined => {
Мне кажется, это не на уровне канваса должно делаться, а в канвас нужно добавить возможность принимать id проекта

2021-02-16 05:34 UTC, Inzephirum requested changes

2021-02-16 05:34 UTC, Inzephirum commented on src/components/canvas/hooks/use-saved-screen.ts
> +  const rawScale = sessionStorage.getItem(canvasScale);
Почти везде, где используется screenSaver есть и работа с sessionStorage. Думаю, что стоит это тогда инкапсулировать в сам ScreenSaverService и покрыть тестами

2021-02-16 05:36 UTC, Inzephirum commented on src/components/canvas/utils.ts
> +export const getProjectIdFromURI = (): string | undefined => {
в библиотеку компонентов вообще не стоит добавлять знаний про предметную область

2021-02-16 17:13 UTC, sergavshin commented on src/components/canvas/constants.ts
> +};
а зачем? разве взаимодействие с sessionStorage по этим ключам будет где-то еще, кроме `ScreenSaverService` ?

2021-02-16 17:13 UTC, sergavshin commented on src/components/canvas/entities/ScreenSaverService.test.ts
> +  });
Тут лучше проверять, что данные сохраняются для разных id. И проверка должна быть не через моки sessionStorage а через вызов методов, которые достают данные из sessionStorage. Сам sessionStorage мокать не надо, он хорошо работает в тестах. Нужно лишь добавить перед тестами хук:
```js
beforeEach(() => {
   sessionStorage.clear();
});

2021-02-16 17:13 UTC, sergavshin commented on src/components/canvas/entities/ScreenSaverService.ts
> +  }
метод не покрыт тестами

2021-02-16 17:13 UTC, sergavshin commented on src/components/canvas/entities/ScreenSaverService.ts
> +  public setStorageCanvasScrollPosition(position: Position): void {
Из всех методов можно убрать слово `Storage`. Сам сервис подразумевает хранение данных где-то, а где именно уже не важно.

2021-02-16 17:13 UTC, sergavshin commented on src/components/canvas/entities/ScreenSaverService.ts
> +  }
этот метод точно теперь нужен в публичном api?

2021-02-16 17:40 UTC, DmitriiBo commented on src/components/canvas/entities/ScreenSaverService.ts
> +  }
уже нет

2021-02-16 17:44 UTC, DmitriiBo commented on src/components/canvas/constants.ts
> +};
только в тестах еще) раз теперь использую подлинный storage - дропнул

2021-02-17 11:37 UTC, maksim-kononov-csssr approved these changes

2021-02-18 08:12 UTC, sergavshin approved these changes

2021-02-18 08:36 UTC, merged