[VEGA-3175] feat(canvas): Добавление подсказки по горячим клавишам для canvas
gpn-prototypes/vega-ui pull request #514
Opened 2021-02-15 14:19 UTC by lipgen

Jira issue: VEGA-3175

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Сторибук: stories соответствует [правилам](https://github.com/gpn-prototypes/vega-ui/blob/master/docs/storybook.md)
- [ ] Верстка: используются [переменные](https://github.com/gpn-prototypes/ui-kit/tree/master/src/components/Theme) и [css-классы](https://github.com/gpn-prototypes/ui-kit/blob/master/src/utils/whitepaper/whitepaper.css) из [дизайн-системы ГПН](https://github.com/gpn-prototypes/ui-kit)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем PR
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2021-02-16 06:20 UTC, Inzephirum requested changes

2021-02-16 06:20 UTC, Inzephirum commented on src/components/canvas/components/HotkeyPrompt/HotkeyPrompt.test.tsx
> +  const promptButton = screen.getByTestId('hotkey-prompt-button');
```suggestion
  const promptButton = screen.getByRole('button', { name: 'Подсказка по сокращениям клавиш' });
```

2021-02-16 06:20 UTC, Inzephirum commented on src/components/canvas/components/HotkeyPrompt/HotkeyPrompt.test.tsx
> +    expect(prompt).toBeInTheDocument();
```suggestion
    expect(prompt).toBeVisible();
```

2021-02-16 06:20 UTC, Inzephirum commented on src/components/canvas/components/HotkeyPrompt/HotkeyPrompt.test.tsx
> +    let prompt = component.queryByTestId('hotkey-prompt');
Когда это возможно, стоит избегать использование `data-testid`. Вместо этого, лучше искать элементы по атрибутам доступным для пользователя. Это могут быть: "aria" атрибуты, text, title, label, различные интерактивные элементы, через которые пользователь может взаимодействовать с системой

2021-02-16 06:20 UTC, Inzephirum commented on src/components/canvas/components/HotkeyPrompt/HotkeyPrompt.test.tsx
> +  fireEvent.click(promptButton);
Лучше использовать `userEvent.click` из `@testing-library/user-event`, Он эмулирует действия пользователя ближе к реальному

2021-02-16 06:20 UTC, Inzephirum commented on src/components/canvas/components/HotkeyPrompt/HotkeyPrompt.tsx
> +            {React.Children.toArray(
для чего `React.Children.toArray` ? Кажется, что и без него должно все работать как надо

2021-02-16 06:20 UTC, Inzephirum commented on src/components/canvas/components/HotkeyPrompt/HotkeyPrompt.tsx
> +  };
Думаю, что для хоткея лучше сделать отдельный компонент

2021-02-17 09:18 UTC, lipgen commented on src/components/canvas/components/HotkeyPrompt/HotkeyPrompt.tsx
> +            {React.Children.toArray(
Это для того, чтобы вручную не проставлять key для элементов. Без него выдает warning. Либо так, либо вручную проставлять. А так как компонент статичный, и служит только для отображения информации мне кажется можно использовать ```React.Children.ToArray```

2021-02-17 11:59 UTC, maksim-kononov-csssr approved these changes

2021-02-17 14:42 UTC, hitmanet approved these changes

2021-02-18 09:17 UTC, sergavshin approved these changes

2021-02-18 09:18 UTC, sergavshin commented on src/components/canvas/components/HotkeyPrompt/HotkeyPrompt.tsx
> +            {React.Children.toArray(
вручную было бы наглядней

2021-02-18 12:36 UTC, merged