Add notebook.
gpn-prototypes/vega-ui pull request #854
Opened 2022-08-19 08:33 UTC by mokkiebear

## Problem statement

_{Jira issue number, description or crucial excerpts}_

## Solution details

_{What has been done (list of details)}_

## Type
- [ ] Feature
- [ ] Bug Fix
- [ ] Refactoring
- [ ] Test
- [ ] Other

## Associated issues

_{Jira issues or PRs related to this one}_

## Quality control
- [ ] PR: Based on a correct branch
- [ ] PR: Head branch is rebased on the base branch
- [ ] PR: Assignee chosen and necessary labels are set
- [ ] PR: Current form is filled out (where it makes sense)
- [ ] PR: Diff checked for irrelevant changes
- [ ] PR: Commit messages follow [the rules](../docs/commits-style.md)
- [ ] JS: There's no errors/warnings in the browser dev console
- [ ] Layout: Uses [variables](https://github.com/gpn-prototypes/ui-kit/tree/master/src/components/Theme) and [CSS classes](https://github.com/gpn-prototypes/ui-kit/blob/master/src/utils/whitepaper/whitepaper.css) from [GPN design system](https://github.com/gpn-prototypes/ui-kit)
- [ ] Layout: Tested with various content amounts
- [ ] Docs: All changes to the component API are reflected and key points are described
- [ ] Storybook: Stories are written/updated for components
- [ ] Storybook: Stories follow [the rules](https://github.com/gpn-prototypes/vega-ui/blob/master/docs/storybook.md)
- [ ] Tests: New features and bugfixes are covered with tests
- [ ] Tests: Existing tests passed successfully

## Notable statements
- [ ] Affects configuration files
- [ ] Brings new packages or updates existing
- [ ] Opened follow-up tasks to resolve

2022-08-19 08:46 UTC, ndrzhn approved these changes

2022-08-19 08:52 UTC, ndrzhn commented on src/types/notebook.ts
> +}
а где описан тип самого сервиса? а то в модулях не видно его методы

2022-08-19 08:53 UTC, ndrzhn requested changes
написала коммент

2022-08-19 10:21 UTC, ndrzhn commented on src/services/notebookService.ts
> +  getToken: () => Promise<string | null>;
здесь точно null нужен?

2022-08-19 10:36 UTC, ndrzhn commented on src/services/notebookService.ts
> +  getToken: () => Promise<string | null>;
нужен

2022-08-22 05:31 UTC, mokkiebear commented on src/services/notebookService.ts
> +  getToken: () => Promise<string | null>;
Думаю да

2022-08-22 06:53 UTC, SergeyKatugin approved these changes

2022-08-22 09:34 UTC, ndrzhn approved these changes

2022-08-22 09:37 UTC, SergeyKatugin approved these changes

2022-08-22 09:39 UTC, merged